services:
  postgres:
    image: postgres:13-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=masakinDB # The PostgreSQL default database (automatically created at first launch)
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password123
    ports:
      - '5433:5432' # this code equal to ourtside_port:container_port so to change how outside access to container change the first one

volumes:
  db-data:
